### PR TITLE
UPDATE on adminView.vb, UPDATE on Main.vb

### PR DESCRIPTION
**Pull request by monaxx**

### CODE REVIEW

**Review by WansehDev — APPROVED** [review]

**Comment by monaxx** [comment]
Nara updated adminView Lance bay

**Comment by monaxx** [comment]
-UPDATE on adminView,vb
-UPDATE on Main.vb
-MERGED updated adminView.vb and updated Main.vb

-User controls still not fixed

**Comment by DomexCleanerz** [comment]
-UPDATE on adminView,vb
-UPDATE on Main.vb
-MERGED updated adminView.vb and updated Main.vb

-User controls still not fixed

**Comment by WansehDev** [comment]
gi merge na nako mon

**Pull request merged**
